//
//  ContentNotificationViewController.swift
//  Uni
//
//  Created nguyen gia huy on 30/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class ContentNotificationViewController: UIViewController, ContentNotificationViewProtocol {

    @IBOutlet weak var lbTitle: UILabel!
    @IBOutlet weak var lbContent: UILabel!
    @IBOutlet weak var btOk: UIButton!
    var presenter: ContentNotificationPresenterProtocol
    var contentNoti = ""
    var titleNoti = ""

	init(presenter: ContentNotificationPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ContentNotificationViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
        setupUI()
    }
    
    func setupUI(){
        lbTitle.text = titleNoti
        lbContent.text = contentNoti
    }
    @IBAction func btOk(_ sender: Any) {
        dismiss(animated: false, completion: nil)
    }
    
}
