//
//  DatePickerViewViewController.swift
//  Uni
//
//  Created nguyen gia huy on 21/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class DatePickerViewViewController: BaseViewController, DatePickerViewViewProtocol {
    
    @IBOutlet weak var datePicker: UIDatePicker!
    @IBOutlet weak var lbCurrentDate: UILabel!
    var presenter: DatePickerViewPresenterProtocol
    var dataDatePicker: (()->Void)? = nil
    var dataPicker = "Choose Date"
    init(presenter: DatePickerViewPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "DatePickerViewViewController", bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        presenter.viewDidLoad()
        let currentDate = Date()
        datePicker.minimumDate = currentDate
        lbCurrentDate.text = currentPickerDate(pickerDate: datePicker)
        datePicker.setDate(dataPicker.toDateDate(), animated: true)
        lbCurrentDate.textColor = AppColor.YellowFAB32A

    }
    
    @IBAction func datePicker(_ sender: Any) {
        lbCurrentDate.text = currentPickerDate(pickerDate: datePicker)
        
    }
    
    @IBAction func okPickerDate(_ sender: Any) {
        dataPicker = currentPickerDate(pickerDate: datePicker)
        dataDatePicker?()
        dismiss(animated: false, completion: nil)
    }
    @IBAction func cancelPickerDate(_ sender: Any) {
        dismiss(animated: false, completion: nil)
    }
    
}
