//
//  DatePickerViewPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 21/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol DatePickerViewViewProtocol: class {

}

// MARK: Presenter -
protocol DatePickerViewPresenterProtocol: class {
	var view: DatePickerViewViewProtocol? { get set }
    func viewDidLoad()
}

class DatePickerViewPresenter: DatePickerViewPresenterProtocol {

    weak var view: DatePickerViewViewProtocol?

    func viewDidLoad() {

    }
}
