//
//  CreateEventViewController.swift
//  Uni
//
//  Created nguyen gia huy on 19/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class CreateEventViewController: BaseViewController {
    @IBOutlet weak var lbCreateEvent: UILabel!
    @IBOutlet weak var lbTitle: UILabel!
    @IBOutlet weak var lbOverview: UILabel!
    @IBOutlet weak var lbLocation: UILabel!
    @IBOutlet weak var lbDate: UILabel!
    @IBOutlet weak var lbTime: UILabel!
    @IBOutlet weak var lbScore: UILabel!
    @IBOutlet weak var imgLandscape: UIImageView!
    @IBOutlet weak var imgPortal: UIImageView!
    @IBOutlet weak var btImgLandscape: UIButton!
    @IBOutlet weak var btImgPortal: UIButton!
    @IBOutlet weak var contentTitle: UITextField!
    @IBOutlet weak var contentOverview: UITextView!
    @IBOutlet weak var contentLocation: UITextField!
    @IBOutlet weak var btChooseDate: UIButton!
    @IBOutlet weak var btCheckin: UIButton!
    @IBOutlet weak var btCheckout: UIButton!
    @IBOutlet weak var btScore: UIButton!
    @IBOutlet weak var btDone: UIButton!
    @IBOutlet weak var tableViewScore: UITableView!
    var pickerDate: UIDatePicker?
	var presenter: CreateEventPresenterProtocol
    var imagePicker: ImagePicker!
    var scoreEvent = 0
    var refreshListEvent: (()->Void)? = nil
	init(presenter: CreateEventPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "CreateEventViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        setupUI()
        setupLanguage()
    }
    
    func setupLanguage(){
        lbCreateEvent.text = AppLanguage.CreateEvent.CreateEvent.localized
        lbTitle.text = AppLanguage.CreateEvent.Title.localized
        lbOverview.text = AppLanguage.CreateEvent.Overview.localized
        lbLocation.text = AppLanguage.CreateEvent.Location.localized
        lbDate.text = AppLanguage.CreateEvent.Date.localized
        lbTime.text = AppLanguage.CreateEvent.Time.localized
        lbScore.text = AppLanguage.CreateEvent.Score.localized
        btDone.setTitle(AppLanguage.CreateEvent.btDone.localized, for: .normal)
        btChooseDate.setTitle(AppLanguage.CreateEvent.ChooseDate.localized, for: .normal)
        btCheckin.setTitle(AppLanguage.CreateEvent.Checkin.localized, for: .normal)
        btCheckout.setTitle(AppLanguage.CreateEvent.Checkout.localized, for: .normal)
    }
    
    func setupUI(){
        tableViewScore.delegate = self
        tableViewScore.dataSource = self
        tableViewScore.register(UINib(nibName: "TableViewScoreCell", bundle: nil), forCellReuseIdentifier: "TableViewScoreCell")
        
        self.imagePicker = ImagePicker(presentationController: self, delegate: self)
        lbTitle.textColor = AppColor.YellowFAB32A
        lbOverview.textColor = AppColor.YellowFAB32A
        lbLocation.textColor = AppColor.YellowFAB32A
        lbDate.textColor = AppColor.YellowFAB32A
        lbTime.textColor = AppColor.YellowFAB32A
        lbScore.textColor = AppColor.YellowFAB32A
        btDone.backgroundColor = AppColor.YellowFAB32A
        imgPortal.borderColor = AppColor.YellowFBC459
        btDone.shadowColor = AppColor.YellowShadow
        
    }
    
    func datePickerView()
    {
        
        self.pickerDate = UIDatePicker()
        pickerDate?.datePickerMode = .date
        pickerDate?.addTarget(self, action: #selector(dateChanged(datePicker:)), for: .valueChanged)
        
    }
    @objc func dateChanged(datePicker: UIDatePicker){//format date
        btChooseDate.setTitle(getFormattedDate(date: "\(pickerDate!.date)"), for: .normal)
        // view.endEditing(true)
    }
    

    
    @IBAction func btImgPortal(_ sender: UIButton) {
        sender.animationScale()
        imagePicker.present(from: sender,type: .Portal)
    }
    
    @IBAction func btImgLandscape(_ sender: UIButton) {
        sender.animationScale()
        imagePicker.present(from: sender,type: .Landscape)
    }
    
    @IBAction func btChooseDate(_ sender: UIButton) {
        let datePicker = DatePickerViewViewController(presenter: DatePickerViewPresenter())
        datePicker.dataDatePicker = { [self] in
            btChooseDate.setTitle(datePicker.dataPicker, for: .normal)
        }
        datePicker.dataPicker = (btChooseDate.titleLabel?.text)!
        datePicker.modalPresentationStyle = .overCurrentContext
        present(datePicker, animated: false, completion: nil)
    }
    
    @IBAction func btCheckin(_ sender: Any) {
        getTime()
    }
    
    @IBAction func btCheckout(_ sender: Any) {
        getTime()
    }
    
    func getTime() {
        let timePicker = TimePickerViewController(presenter: TimePickerPresenter())
        timePicker.dataTimePicker = { [self] in
            btCheckin.setTitle(timePicker.dateCheckin, for: .normal)
            btCheckout.setTitle(timePicker.dateCheckout, for: .normal)
        }
        
        timePicker.dateCheckin = (btCheckin.titleLabel?.text)!
        timePicker.dateCheckout = (btCheckout.titleLabel?.text)!
        timePicker.modalPresentationStyle = .overCurrentContext
        present(timePicker, animated: false, completion: nil)
    }
    
    @IBAction func btDone(_ sender: Any) {
        if let title = contentTitle.text, let overview = contentOverview.text, let location = contentLocation.text, let date = btChooseDate.titleLabel?.text,let checkin = btCheckin.titleLabel?.text,let checkout = btCheckout.titleLabel?.text {
            
            if checkin != AppLanguage.CreateEvent.Checkin.localized && checkout != AppLanguage.CreateEvent.Checkout.localized && removeWhiteSpaceAndLine(text: overview) != "" && removeWhiteSpaceAndLine(text: title) != "" && removeWhiteSpaceAndLine(text: location) != "" && date != AppLanguage.CreateEvent.ChooseDate.localized {
                
                            showSpinner()
                            presenter.createEvent(urlImgLanscape: "", urlImgPortal: "", title: removeWhiteSpaceAndLine(text: title), overview: removeWhiteSpaceAndLine(text: overview), location: removeWhiteSpaceAndLine(text: location), date: date, checkin: checkin.formatDateCreate(), checkout: checkout.formatDateCreate(), score: scoreEvent)
                
            } else {
                showAlert(title: AppLanguage.HandleError.anError.localized, message: AppLanguage.HandleError.fillIn.localized, actionTitles: [AppLanguage.Ok.localized], style: [.default], actions: [.none])
            }
        } else {return}
        
    }
    
}
extension CreateEventViewController: ImagePickerDelegate {
    func didSelect(image: UIImage?, type: typeImage) {
        switch type {
        case .Landscape:
            imgLandscape.image = image
            imgPortal.layer.borderWidth = 1
            imgPortal.layer.borderColor = AppColor.YellowFAB32A.cgColor
        case .Portal:
            imgPortal.image = image
            
        }
    }

}

extension CreateEventViewController: CreateEventViewProtocol {
    func pushNotificationSuccess() {
        presentAlertWithTitle(title: AppLanguage.HandleSuccess.Success.localized, message: AppLanguage.HandleSuccess.pushNotification.localized, options: AppLanguage.Ok.localized) { (Int) in}
    }
    
    func pushNotificationFailed() {
        presentAlertWithTitle(title: AppLanguage.HandleError.anError.localized, message: AppLanguage.HandleError.pushNotification.localized, options: AppLanguage.Ok.localized) { (Int) in}
    }
    
    func createEventSuccess(path: String, title: String) {
        removeSpinner()
        presenter.sendPushNotification(to: "", title: "New event!!!", body: "Hi, we have just added \(title) event in the Uni.\nWe will be happy if you join us.\nLets explore.")
        presentAlertWithTitle(title: AppLanguage.HandleSuccess.Success.localized, message: AppLanguage.HandleSuccess.createEvent.localized, options: AppLanguage.Ok.localized) { [self] (option) in
            self.navigationController?.popViewController(animated: true)
            refreshListEvent?()
    }
       
        if let imageLanscape = imgLandscape.image, let imagePortal = imgPortal.image{
            presenter.uploadImage(images: [imageLanscape,imagePortal],path: path)
        } else {return}
        
        
    }
    
    func uploadImageLandscapeSuccess(keyRef: String, pathEvent: String) {
        presenter.updateImageEvent(keyRef: keyRef, path: pathEvent, type: .Landscape)
        removeSpinner()
    }
    
    func uploadImagePortalSuccess(keyRef: String, pathEvent: String) {
        presenter.updateImageEvent(keyRef: keyRef, path: pathEvent, type: .Portal)
        removeSpinner()
    }
    
    func uploadImageLandscapeFailed() {
        print("Upload image lanscape failed")
        removeSpinner()
    }
    
    func uploadImagePortalFailed() {
        print("Upload image portal failed")
        removeSpinner()
    }

    func createEventFailed() {
        removeSpinner()
        presentAlertWithTitle(title: AppLanguage.HandleError.anError.localized, message: AppLanguage.HandleError.createEvent.localized, options: AppLanguage.Ok.localized) { [] (option) in
        }
       
    }
    
    
}

extension CreateEventViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return btScore.frame.height
    }
}

extension CreateEventViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 21
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "TableViewScoreCell", for: indexPath) as? TableViewScoreCell {
            cell.lbScore.text = "\(indexPath.row)"
            print(indexPath.row)
            return cell
        } else {
            return UITableViewCell()
        }
        
    }
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        scoreEvent = indexPath.row
    }
    
}
