//
//  SettingPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 30/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SettingViewProtocol: class {

}

// MARK: Presenter -
protocol SettingPresenterProtocol: class {
	var view: SettingViewProtocol? { get set }
    func viewDidLoad()
}

class SettingPresenter: SettingPresenterProtocol {

    weak var view: SettingViewProtocol?

    func viewDidLoad() {

    }
}
