//
//  PickerDataPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol PickerDataViewProtocol: class {

}

// MARK: Presenter -
protocol PickerDataPresenterProtocol: class {
	var view: PickerDataViewProtocol? { get set }
    func viewDidLoad()
}

class PickerDataPresenter: PickerDataPresenterProtocol {

    weak var view: PickerDataViewProtocol?

    func viewDidLoad() {

    }
}
