//
//  SlideMenuPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 10/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import FirebaseDatabase
import FirebaseAuth
import Firebase
import UIKit
// MARK: View -
protocol SlideMenuViewProtocol: class {
    func signOutSuccess()
    func signOutFailed()
}

// MARK: Presenter -
protocol SlideMenuPresenterProtocol: class {
	var view: SlideMenuViewProtocol? { get set }
    func signOut()
}

class SlideMenuPresenter: SlideMenuPresenterProtocol {

    weak var view: SlideMenuViewProtocol?

    func signOut() {
        do {
            try Auth.auth().signOut()
            view?.signOutSuccess()
            
        } catch _ {
            view?.signOutFailed()
        }
    }
}
