//
//  SlideMenuPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 10/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SlideMenuViewProtocol: class {

}

// MARK: Presenter -
protocol SlideMenuPresenterProtocol: class {
	var view: SlideMenuViewProtocol? { get set }
    func viewDidLoad()
}

class SlideMenuPresenter: SlideMenuPresenterProtocol {

    weak var view: SlideMenuViewProtocol?

    func viewDidLoad() {

    }
}
