//
//  SearchAppHomePresenter.swift
//  Uni
//
//  Created nguyen gia huy on 06/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SearchAppHomeViewProtocol: class {

}

// MARK: Presenter -
protocol SearchAppHomePresenterProtocol: class {
	var view: SearchAppHomeViewProtocol? { get set }
    func viewDidLoad()
}

class SearchAppHomePresenter: SearchAppHomePresenterProtocol {

    weak var view: SearchAppHomeViewProtocol?

    func viewDidLoad() {

    }
}
