//
//  LoginPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol LoginViewProtocol: class {

}

// MARK: Presenter -
protocol LoginPresenterProtocol: class {
	var view: LoginViewProtocol? { get set }
    func viewDidLoad()
}

class LoginPresenter: LoginPresenterProtocol {

    weak var view: LoginViewProtocol?

    func viewDidLoad() {

    }
}
