//
//  LoginPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import FirebaseDatabase
import FirebaseAuth
import Firebase
import UIKit
// MARK: View -
protocol LoginViewProtocol: class {
    func loginSuccess()
    func loginFailed()
}

// MARK: Presenter -
protocol LoginPresenterProtocol: class {
	var view: LoginViewProtocol? { get set }
    func siginIn()
}

class LoginPresenter: LoginPresenterProtocol {
    weak var view: LoginViewProtocol?
    
    func siginIn() {
        Auth.auth().signIn(withEmail: "test@gmail.com", password:"123456") { [weak self] user, error in
            guard self != nil else { return }
            if user != nil {
                let user = Auth.auth().currentUser
                print("User loggin in with data: \(user!.uid)")
            }
            else
            {
                print(error?.localizedDescription ?? "")
            }
            
            
        }
    }
    
}
