//
//  AppHomePresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol AppHomeViewProtocol: class {
}

// MARK: Presenter -
protocol AppHomePresenterProtocol: class {
	var view: AppHomeViewProtocol? { get set }
}

class AppHomePresenter: AppHomePresenterProtocol {
    weak var view: AppHomeViewProtocol?
}
