//
//  DetailEventViewController.swift
//  Uni
//
//  Created nguyen gia huy on 03/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class DetailEventViewController: UIViewController, DetailEventViewProtocol {

	var presenter: DetailEventPresenterProtocol

	init(presenter: DetailEventPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "DetailEventViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }
    @IBAction func backVC(_ sender: Any) {
        self.navigationController?.popViewController(animated: true)
    }
    
}
