//
//  DetailEventPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 03/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol DetailEventViewProtocol: class {

}

// MARK: Presenter -
protocol DetailEventPresenterProtocol: class {
	var view: DetailEventViewProtocol? { get set }
    func viewDidLoad()
}

class DetailEventPresenter: DetailEventPresenterProtocol {

    weak var view: DetailEventViewProtocol?

    func viewDidLoad() {

    }
}
