//
//  ForgotPasswordPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol ForgotPasswordViewProtocol: class {

}

// MARK: Presenter -
protocol ForgotPasswordPresenterProtocol: class {
	var view: ForgotPasswordViewProtocol? { get set }
    func viewDidLoad()
}

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol {

    weak var view: ForgotPasswordViewProtocol?

    func viewDidLoad() {

    }
}
