//
//  ForgotPasswordViewController.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import UIKit

class ForgotPasswordViewController: UIViewController{

    @IBOutlet weak var txtEmail: UITextField!
    @IBOutlet weak var lbTime: UILabel!
    @IBOutlet weak var btSend: UIButton!
    var presenter: ForgotPasswordPresenterProtocol
    var counter = 15
    var resendTimer = Timer()
	init(presenter: ForgotPasswordPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ForgotPasswordViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
    
        
    }
    
    @IBAction func btSend(_ sender: Any) {
        presenter.sendEmailResetPassword(email: txtEmail.text!)
        
        
    }
    
     @objc func updateCounter() {
        
        if counter > -1 {
            lbTime.isHidden = false
            lbTime.text = "\(counter)s"
            print(counter)
            counter -= 1

        } else {
            resendTimer.invalidate()
            lbTime.isHidden = true
            btSend.isEnabled = true
            
        }
    }
    
    
}

extension ForgotPasswordViewController: ForgotPasswordViewProtocol {
    func sendSuccess() {
        print("Send Success")
        counter = 15
        resendTimer = Timer.scheduledTimer(timeInterval: 1.0, target: self, selector: #selector(updateCounter), userInfo: nil, repeats: true)
        btSend.isEnabled = false
        lbTime.isHidden = false
        //navigationController?.popToRootViewController(animated: true)
    }
    
    func sendFailed(error: Error!) {
        print(error.localizedDescription)
    }
    
    
}
