//
//  ForgotPasswordViewController.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class ForgotPasswordViewController: UIViewController, ForgotPasswordViewProtocol {

    @IBOutlet weak var btSend: UIButton!
    var presenter: ForgotPasswordPresenterProtocol

	init(presenter: ForgotPasswordPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ForgotPasswordViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
        desginUI()
    }
    
    func desginUI(){
    }

    @IBAction func gotoLoginVC(_ sender: Any) {
        //let LoginVC = LoginViewController(presenter: LoginPresenter())
        self.navigationController?.popViewController(animated: true)
    }
}
