//
//  ForgotPasswordPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 02/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import FirebaseDatabase
import FirebaseAuth
import Firebase

// MARK: View -
protocol ForgotPasswordViewProtocol: class {
    func sendSuccess()
    func sendFailed(error: Error!)
}

// MARK: Presenter -
protocol ForgotPasswordPresenterProtocol: class {
	var view: ForgotPasswordViewProtocol? { get set }
    func sendEmailResetPassword(email: String)
}

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol {
    weak var view: ForgotPasswordViewProtocol?
    
    func sendEmailResetPassword(email: String) {
        Auth.auth().sendPasswordReset(withEmail: email) { [self] error in
            if(error != nil)
            {
                view?.sendFailed(error: error)
            }
            else
            {
                view?.sendSuccess()
            }
        }
    }

}
