//
//  BarcodePresenter.swift
//  Uni
//
//  Created nguyen gia huy on 10/11/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol BarcodeViewProtocol: class {

}

// MARK: Presenter -
protocol BarcodePresenterProtocol: class {
	var view: BarcodeViewProtocol? { get set }
    func viewDidLoad()
}

class BarcodePresenter: BarcodePresenterProtocol {

    weak var view: BarcodeViewProtocol?

    func viewDidLoad() {

    }
}
