//
//  PushNotificationViewController.swift
//  Uni
//
//  Created nguyen gia huy on 11/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class PushNotificationViewController: BaseViewController {
    
    @IBOutlet weak var txtTitle: UITextField!
    @IBOutlet weak var txtContent: UITextView!
    @IBOutlet weak var lbSentNotice: UILabel!
    @IBOutlet weak var btSentNotice: UIButton!
    @IBOutlet weak var lbContent: UILabel!
    @IBOutlet weak var lbTitle: UILabel!
    var presenter: PushNotificationPresenterProtocol
    init(presenter: PushNotificationPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "PushNotificationViewController", bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.view = self
        setupLanguage()
        setupUI()
        
    }
    
    func setupLanguage() {
        lbTitle.text = AppLanguage.Title.localized
        lbContent.text = AppLanguage.Content.localized
        lbSentNotice.text = AppLanguage.Manage.SendNotice.localized
    }
    
    func setupUI() {
        btSentNotice.setTitle(AppLanguage.CreateUser.Done.localized, for: .normal)
        btSentNotice.backgroundColor = AppColor.YellowFAB32A
        btSentNotice.shadowColor = AppColor.YellowShadow
    }
    
    @IBAction func sentNotice(_ sender: Any) {
        if let title = txtTitle.text, let content = txtContent.text {
            if removeWhiteSpaceAndLine(text: title) != "" && removeWhiteSpaceAndLine(text: content) != "" {
                presenter.sendPushNotification(to: "", title: removeWhiteSpaceAndLine(text: title), body: removeWhiteSpaceAndLine(text: content))
                
            } else {
                presentAlertWithTitle(title: AppLanguage.HandleError.anError.localized, message:
                                        AppLanguage.HandleError.fillIn.localized, options: AppLanguage.Ok.localized) { (Int) in}
            }
        } else { return }
        
    }
    
}

extension PushNotificationViewController: PushNotificationViewProtocol {
    func pushNotificationSuccess() {
        presentAlertWithTitle(title: AppLanguage.HandleSuccess.Success.localized, message: AppLanguage.HandleSuccess.pushNotification.localized, options: AppLanguage.Ok.localized) { (Int) in}
    }
    
    func pushNotificationFailed() {
        presentAlertWithTitle(title: AppLanguage.HandleError.anError.localized, message: AppLanguage.HandleError.pushNotification.localized, options: AppLanguage.Ok.localized) { (Int) in}
    }
    
    
}
