//
//  PushNotificationPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 11/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol PushNotificationViewProtocol: class {

}

// MARK: Presenter -
protocol PushNotificationPresenterProtocol: class {
	var view: PushNotificationViewProtocol? { get set }
    func viewDidLoad()
}

class PushNotificationPresenter: PushNotificationPresenterProtocol {

    weak var view: PushNotificationViewProtocol?

    func viewDidLoad() {

    }
}
