//
//  PushNotificationViewController.swift
//  Uni
//
//  Created nguyen gia huy on 11/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class PushNotificationViewController: BaseViewController, PushNotificationViewProtocol {

    @IBOutlet weak var txtTitle: UITextField!
    @IBOutlet weak var txtContent: UITextView!
    @IBOutlet weak var lbSentNotice: UILabel!
    @IBOutlet weak var btSentNotice: UIButton!
    @IBOutlet weak var lbContent: UILabel!
    @IBOutlet weak var lbTitle: UILabel!
    var presenter: PushNotificationPresenterProtocol
    let senderPushNotice = PushNotificationSender()
	init(presenter: PushNotificationPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "PushNotificationViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
        setupLanguage()
        setupUI()
        
    }
    
    func setupLanguage() {
        lbTitle.text = AppLanguage.Title.localized
        lbContent.text = AppLanguage.Content.localized
        lbSentNotice.text = AppLanguage.Manage.SendNotice.localized
    }
    
    func setupUI() {
        btSentNotice.setTitle(AppLanguage.CreateUser.Done.localized, for: .normal)
        btSentNotice.backgroundColor = AppColor.YellowFAB32A
        btSentNotice.shadowColor = AppColor.YellowShadow
    }
    
    @IBAction func sentNotice(_ sender: Any) {
        if let title = txtTitle.text, let content = txtContent.text {
            if title == "" || content == "" {
                presentAlertWithTitle(title: AppLanguage.HandleError.anError.localized, message: AppLanguage.HandleError.fillIn.localized, options: AppLanguage.Ok.localized) { (Int) in}
            } else {
                senderPushNotice.sendPushNotification(to: "", title: title, body: content)
            }
        } else { return }
        
    }
    
}
