//
//  PushNotificationViewController.swift
//  Uni
//
//  Created nguyen gia huy on 11/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class PushNotificationViewController: UIViewController, PushNotificationViewProtocol {

    @IBOutlet weak var txtTitle: UITextField!
    @IBOutlet weak var txtContent: UITextView!
    @IBOutlet weak var lbSentNotice: UILabel!
    @IBOutlet weak var btSentNotice: UIButton!
    var presenter: PushNotificationPresenterProtocol
    let senderPushNotice = PushNotificationSender()
	init(presenter: PushNotificationPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "PushNotificationViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }
    @IBAction func sentNotice(_ sender: Any) {
        if let title = txtTitle.text, let content = txtContent.text {
            senderPushNotice.sendPushNotification(to: "", title: title, body: content)
        } else { return }
        
    }
    
}
