//
//  PrivacyPolicyPresenter.swift
//  Uni
//
//  Created nguyen gia huy on 01/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol PrivacyPolicyViewProtocol: class {

}

// MARK: Presenter -
protocol PrivacyPolicyPresenterProtocol: class {
	var view: PrivacyPolicyViewProtocol? { get set }
    func viewDidLoad()
}

class PrivacyPolicyPresenter: PrivacyPolicyPresenterProtocol {

    weak var view: PrivacyPolicyViewProtocol?

    func viewDidLoad() {

    }
}
