//
//  PrivacyPolicyViewController.swift
//  Uni
//
//  Created nguyen gia huy on 01/12/2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class PrivacyPolicyViewController: BaseViewController, PrivacyPolicyViewProtocol {

    @IBOutlet weak var contentPrivacyPolicy: UILabel!
    @IBOutlet weak var privacypolicy: UILabel!
    var presenter: PrivacyPolicyPresenterProtocol

	init(presenter: PrivacyPolicyPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "PrivacyPolicyViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
        setupLanguage()
        addNav()
    }
    
    func setupLanguage(){
        privacypolicy.text = AppLanguage.Privacy.PrivacyPolicy.localized
        contentPrivacyPolicy.text = AppLanguage.Privacy.ContentPrivacyPolicy.localized
    }
    
    func addNav() {
        addMenuButton()
        addButtonImageToNavigation(image: AppIcon.icBellYellow!, style: .right, action: #selector(notification))
        self.navigationController?.hideShadowLine()
    }
    
    @objc func notification(){

    }
}
